### ISSUE TITLE
HiveMQ node reports ready when in terminating state. 

### ISSUE THREAD

**Issue by adamcrane** [hivemq/hivemq-heartbeat-extension#2]
## Expected behavior
When calling `System.exit(1)` from an extension, traffic should no longer be routed to the HiveMQ node as it is shutting down.

## Actual behavior
HiveMQ begins to shutdown, but it still receives traffic. Because there is sustained traffic to the node, it will never shutdown.

## Details
- Using HiveMQ 4.2.0 

## Suggested Change
Add `UNAVAILABLE` to ```LifeCycleStage``` so that new traffic is not routed to nodes that are trying to shutdown.

**Comment by fraschbi** [comment]
Hey Adam,

Thank you for your patience. As we discussed on our support portal, the cause for the behaviour you are seeing is actually the blocking nature of the System.exit(1) call.

Regards,
Florian
